name: 'istioctl analyze'
description: 'Runs istioctl analyze on configuration'
inputs: 
  config-dir:
    description: 'Directory containing config to analyze'
    required: true  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.config-dir }}
#  args: ['-c', 'find cluster -type f -name \*.yaml -print0 | xargs -0 istioctl analyze -A']