name: 'istioctl analyze'
description: 'Runs istioctl analyze on configuration'
inputs: 
  configDir:
    description: 'Directory containing config to analyze'
    required: true
  repoToken:
    description: 'Github token for the repo to use'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.configDir }}
